### PR TITLE
Improve the PKGBUILD

### PR DESCRIPTION
**Pull request by IslandC0der**
1. Split the PKGBUILD into stable and git versions;
2. Removed redundant dependencies (they are either already part of `base` or `base-devel`);
3. Move the compiling into the `build()` function;
4. Make `pkgver()` more detailed;
5. Other small tweaks, to comply with [the Arch guidelines.](https://wiki.archlinux.org/title/Arch_package_guidelines)

### CODE REVIEW

**Comment by mcdope** [comment]
Thanks for your PR (and the AUR submission, my google alert triggered 😆 )

This will also need some Makefile adjustment so the arch/zst target wont break, which I will do tomorrow. 

If I understand your PKGBUILD correctly for stable it looks for tags like "x.y.z", right?

**Comment by IslandC0der** [comment]
Thanks :))

Yeah, it will look on the archive for what I set the `$pkgver` to be, which I will do according to the latest published tag.
Now, I have noticed that some tags start with a `v`, and this could problematic, since it interacts with the version comparison algorithm in unexpected ways (so for example, `v0.8.0` would be interpreted as being lesser than `0.7.3`, thus being treated as a downgrade). 

Do you know of any workarounds? If not, I can also just directly add the `v` to the link in the source array when necessary, to keep it out of the `$pkgver`.

**Comment by mcdope** [comment]
> Now, I have noticed that some tags start with a `v`, and this could problematic, since it interacts with the version comparison algorithm in unexpected ways (so for example, `v0.8.0` would be interpreted as being lesser than `0.7.3`, thus being treated as a downgrade).

I think we shouldn't worry about that. It affects only two versions, which are both legacy/unsupported anyway. If someone seriously want to build them he or she will find out how to do so.

**Comment by mcdope** [comment]
@IslandC0der There will be a new release soon (more or less), how do we want to handle updates to the PKGBUILDs? Will you maintain them or should I just bump the version on each release?

**Pull request merged**
